apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: plndr-cloud-provider
  namespace: kube-system
spec:
  containers:
  - command:
    - /plndr-cloud-provider
    - --cidr 
    - 192.168.0.80/29
    image: plndr/plndr-cloud-provider:0.1.1
    name: plndr-cloud-provider
    imagePullPolicy: Always
    resources: {}
  hostNetwork: true
  serviceAccountName: cloud-controller-manager
